version: "3"
services:
  wiremock:
    image: wiremock/wiremock:latest
    ports:
      - "8000:8080"
    volumes:
      - ./wiremock/mappings:/home/wiremock/mappings
      - ./wiremock/__files:/home/wiremock/__files
    command: [ "--verbose" ]

  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      WIREMOCK_BASE_URL: ${WIREMOCK_BASE_URL}
      WIREMOCK_FORECAST_API: ${WIREMOCK_FORECAST_API}
    depends_on:
      - wiremock





